Training started...
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.models' has no attribute 'naim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 12, in <module>
    def set_naim_params(model_cfg: dict, preprocessing_params: Union[dict, DictConfig], train_set: SupervisedTabularDatasetTorch, **_) -> dict:
NameError: name 'Union' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.naim.NAIMclassifier':
NameError("name 'Union' is not defined")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 284, in <module>
    main()
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 280, in main
    train(config.default)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 70, in train
    model = hydra.utils.instantiate(config.model.model)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.naim.NAIMclassifier', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: default.model.model
