Training started...
Error executing job with overrides: []                                                                                                           
Traceback (most recent call last):
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 280, in main
    train(config.default)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 105, in train
    output = model(features)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 341, in forward
    return self.naim(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 321, in forward
    embeddings = encoder_layer(embeddings, mask=masks, mask2=masks2)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 220, in forward
    inp_x = self.layer_norm_1(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 217, in forward
    return F.layer_norm(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/functional.py", line 2910, in layer_norm
    return torch.layer_norm(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
