Training started...
Error executing job with overrides: []                                                                                            
[2025-04-10 05:49:44,465][__main__][INFO] - Train Epoch: 0 [0/51 (0%)]	Loss: 1.371976
Traceback (most recent call last):
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 277, in main
    train(config.default)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 102, in train
    output = model(features)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 341, in forward
    return self.naim(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 311, in forward
    single_feature_embedding = self.embeddings[feature_idx](single_feature, feature_values)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/tabular_tokenizer.py", line 116, in forward
    x = self.embeddings(x.long() + self.category_offsets[None])
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/functional.py", line 2550, in embedding
    _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/functional.py", line 2434, in _no_grad_embedding_renorm_
    torch.embedding_renorm_(weight.detach(), input, max_norm, norm_type)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
